### ISSUE TITLE
Obliquity

### ISSUE THREAD

**Issue by Roshex** [SethFusion/US2-to-SE-Converter#3]
https://github.com/SethFusion/US2-to-SE-Converter/blob/6d0ae88b22832193f8d8bec2eff1a98bbcbf6f27/US2%20to%20SE%20Converter/US2%20to%20SE%20Converter.cpp#L390

Last question - isn't it supposed to print obliquity / axial tilt, too?

**Comment by SethFusion** [comment]
So I output rotation period because it is a fairly easy thing to calculate from the way it is stored in the simulation file. But obliquity is harder because, in the simulation file, I need to process the angular velocity somehow to produce an obliquity relative to the object's orbital plane. And I do not know this equation. At least, I don't know it well enough to implement it. But in the future, once I've learned it, I've already got code that brings in the angular velocity, even if it is not used right now.
