### ISSUE TITLE
Spin bug

### ISSUE THREAD

**Issue by Roshex** [SethFusion/US2-to-SE-Converter#4]
https://github.com/SethFusion/US2-to-SE-Converter/blob/6d0ae88b22832193f8d8bec2eff1a98bbcbf6f27/US2%20to%20SE%20Converter/US2%20to%20SE%20Converter.cpp#L768

Need to calculate the magnitude first - not all bodies spin exclusively on the y axis (at least in my sim)

**Comment by SethFusion** [comment]
The value US stores in the simulation file seem to already be the magnitude. In fact, it looks like this:
`"AngularVelocity":"0;-7.29211533325724E-05;0",`

This is the angular velocity of Earth as stored in a simulation file. As you can see, x and z are both 0, so the magnitude equation would only spit out the square root of the y value squared, which is just the absolute value of y. 
`sqrt(pow(x, 2) + pow(y, 2) + pow(z, 2))`

So obviously: `sqrt(pow(0, 2) + pow(-7.3E-05, 2) + pow(0, 2)) = 7.3E-05`

And this works. If we solve out this equation with the rest of the rotation period equation, we get this:
`(2 * PI) / abs(-7.3E-05) ~= 86164`
`86164 / 3600 ~= 23.9`
And of course, 23.9 is the rotation period of Earth in hours, which is what SE uses to render the object. (Notice the abs() function. We know the output of calling the magnitude function is the same as if we took the absolute value of y, so we can skip calculating the magnitude.)

Now your problem is that a planet like Venus might rotate in the opposite direction, but this would be solved if obliquity were calculated, which as I said in another post, I cannot do right now. In fact, if you solve the equation for Venus, you will see the rotation period in hours is correct, but its axial tilt, obviously, is not taken into consideration. 

So once I can calculate obliquity properly, this shouldn't be an issue.
